### ISSUE TITLE
npm install fails on windows due to kexec!

### ISSUE THREAD

**Issue by bhaveshgohel** [hemanth/node-nightly#10]
The installation is failing on Windows right now due to kexec because Windows uses Posix APIs! 
There is an issue open for the discussion here: https://github.com/jprichardson/node-kexec/issues/19

**Comment by hemanth** [comment]
@bhaveshgohel Any luck on looking for an alternative?

**Comment by bhaveshgohel** [comment]
@hemanth I tried to compile kexec using missing library for windows but no luck. Will post here if i can find any solution. :smiley:

**Comment by tarungarg546** [comment]
I was banging my head around this from 3 days to solve this but no luck.

This is one the issues where **windows sucks[Though i am using it with bash].**
Other issues i found is using `child_process.spawn` in windows .

**Comment by tarungarg546** [comment]
Hey @bhaveshgohel ,

You can track update of windows [here](https://github.com/tarungarg546/node-nightly/tree/windows), remember it's still in pre-alpha phase.

Ideas are always welcome!
https://github.com/tarungarg546/node-nightly/tree/windows

**Comment by bhaveshgohel** [comment]
Track the pull request https://github.com/hemanth/node-nightly/pull/22
