### ISSUE TITLE
EMFILE: too many open files, open

### ISSUE THREAD

**Issue by gdi2290** [hemanth/node-nightly#17]
ran into this problem with running with webpack 
```
{ Error: EMFILE: too many open files, open '/Users/Hendrixer/.nvm/versions/node/v6.2.1/lib/node_modules/node-nightly/node-v7.0.0-nightly20160722b3127df59a-darwin-x64/lib/node_modules/npm/node_modules/iferr/index.js'
    at Error (native)
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/Users/Hendrixer/.nvm/versions/node/v6.2.1/lib/node_modules/node-nightly/node-v7.0.0-nightly20160722b3127df59a-darwin-x64/lib/node_modules/npm/node_modules/iferr/index.js' }
```

**Comment by tarungarg546** [comment]
Yeah, this is a error in some OS.
Try changing your limit of open files...
by something like `ulimit -n` i dont exactly remember the command.

@hemanth We should consider using `graceful-fs` instead of `fs`, i tested there is no such error when we use `graceful-fs`.

**Comment by hemanth** [comment]
@gdi2290 Thanks for reporting.

@tarungarg546 [this](https://github.com/hemanth/node-nightly/blob/master/index.js#L27) is the potential culprit, we must send a PR to fix that module,rather than switching to `graceful-fs` ?

**Comment by tarungarg546** [comment]
@hemanth if we can do that, it would be great. 

But,  [`graceful-fs`](https://www.npmjs.com/package/graceful-fs) is now considered as `drop-in` replacement of `fs` and it's also built by one of the maintainers of nodeJS and creator npm `isaacs`, so there should be some compatibility issues with node.


But let's refrain us from guessing anything if we can do that without using any module then it would be more than awesome.

**Comment by hemanth** [comment]
@tarungarg546 More the number of module must better actually, but want to know the specifics, I am aware of `graceful-fs` and yes @isaacs can give us great insights indeed!
