### ISSUE TITLE
Any plans to support windows?

### ISSUE THREAD

**Issue by bazjapan** [hemanth/node-nightly#19]

**Comment by tarungarg546** [comment]
@bazjapan i am working on it.
It got delayed due to some personal work, i'll update in 2-3 days hopefully.

**Comment by bazjapan** [comment]
thanks for the heads up.

**Comment by tarungarg546** [comment]
Hey @bazjapan Track update [here](https://github.com/tarungarg546/node-nightly/tree/windows)
