### ISSUE TITLE
change upgrade flow

### ISSUE THREAD

**Issue by paulirish** [hemanth/node-nightly#2]
I don't think you should do a Firefox-style upgrade prompt. "hey i know you're trying to start using firefox but do you want to interrupt what you're doing to see if you wanna upgrade." :p
 
The common action is people will be repeatedly running node-nightly with inspect flags, and you don't want to respond with "N" each time.

I _was_ thinking about something that passively notified you when quitting the node process.. like..

```sh
> node-nightly --inspect index.js
Log from index.js!
^C
New nightly available. To upgrade: `node-nightly --upgrade`
> 
```

_However_, I think that'll be too noisy, even. I think it's better to leave that up to the user and just allow a `--upgrade` flag they can use whenever they want.

wdyt?

**Comment by hemanth** [comment]
Reducing noise SGTM.

We can give a `--help` like any other cli tool and state `--upgrade` there?

**Comment by paulirish** [comment]
Yup sg!

**Comment by hemanth** [comment]
I am just delegating `--help` to the `node` binary and working on the `--upgrade` flag.

**Comment by hemanth** [comment]
There we go!

![](https://github.com/hemanth/node-nightly/raw/master/node-nightly.gif)
