### ISSUE TITLE
404 - node-nightly

### ISSUE THREAD

**Issue by bvjebin** [hemanth/node-nightly#25]
Just tried node-nightly. Following is what I am getting on first time usage of the command `node-nightly`

`
{ [HTTPError: Response code 404 (Not Found)]
  message: 'Response code 404 (Not Found)',
  host: 'nodejs.org',
  hostname: 'nodejs.org',
  method: 'GET',
  path: '/download/nightly/v7.0.0-nightly201608085111e789e6/node-v7.0.0-nightly201608085111e789e6-darwin-x64.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found',
  bufferedData: <Buffer > }
`

What happened to the download link? Why 404? Am I missing something?

I am using Mac El Capitan. 
Node - v5.2.0
NPM - 3.3.12

**Comment by hemanth** [comment]
Thanks for reporting .

Yikes, maybe the latest PR broke it.

//cc @bhaveshgohel 

P.S: We badly need a test suite here.

**Comment by bhaveshgohel** [comment]
@hemanth : The latest release for "darwin" Is not updated on official directory yet! Please check: https://nodejs.org/download/nightly/v7.0.0-nightly201608085111e789e6/

![node-nightly](https://cloud.githubusercontent.com/assets/5253753/17505626/0dee38ce-5e20-11e6-9bd4-4f71d0ac6621.png)

**Comment by hemanth** [comment]
Yup, just noticed! 

We better prompt a message in this case?

**Comment by hemanth** [comment]
@bhaveshgohel @bvjebin [re-tweet](https://twitter.com/GNUmanth/status/762884125980188672) ;)

**Comment by bhaveshgohel** [comment]
@hemanth It will be nice if we can somehow download the 2nd latest release and at upgrade if we get 404 we can prompt it like no update available, and download and prompt it next time when we get. What you think? How can we get the previous release?

**Comment by hemanth** [comment]
Yes, I understand it's hacky, but looking for a quick fix.

Currently we are using `node-nightly-version` to get the latest version, we have two options:

* Create `node-nightly-versions` or

* Create options for `node-nightly-version` to return all the version.

**Comment by bhaveshgohel** [comment]
One quick fix we can do right now is always download the 2nd latest version and if user need the latest he can add "--force-upgrade" kind of flag ?

small code change :
```code
text.split('\n')[1].split('\t')[0])
```
to
```code
text.split('\n')[2].split('\t')[0])
```

**Comment by hemanth** [comment]
I would vote for throwing an error saying we don't have a build yet for this version of OS.

**Comment by bhaveshgohel** [comment]
Downgrading one version will be good, as he can at-least use "node-nightly"! #IMO
And Additionally we can throw error too if we can't get 2nd latest release for that OS.

**Comment by hemanth** [comment]
okies we can do that, but we need to rename `--force-upgrade` to something better.

**Comment by tarungarg546** [comment]
If i were to say, i would personally prefer more interaction in this case.

I would like to see my console like this 

```
Downloading the nightly version, hang on...
Oops! Seems like there is no build ${version} available for ${your-os}
Would you like to fallback to older version(Y/N)?
..${Then do  stuff here} 
```

**Comment by bhaveshgohel** [comment]
@tarungarg546 Good idea! :+1:

**Comment by vigneshshanmugam** [comment]
I would go for a `env` variable or `args` to specify the version to download. 

would address most cases.

**Comment by tarungarg546** [comment]
@vigneshshanmugam but thing is most people dont know abut nightly builds and from where to get them, that's why may be we have this kind of tool available.
If they knew version and all they could just go on the url and download them.
_it's just my view_

**Comment by cswl** [comment]
If the changes don't affect a platform they are not built.. nightlty doesn't necessarily mean a new build every night.

**Comment by bhaveshgohel** [comment]
@hemanth Just check the https://nodejs.org/download/nightly/ they haven't uploaded binaries for linux and MAC since 8th august to till date. I guess the approach i was suggesting for fetching 2nd latest might not work now. And it's good if we just throw an Error saying the build is not available yet. and give them chance to specify the build version they want to download with "--get" or  "--fetch" argument or after throwing error where user will specifying build number like "201608104878e1c0e5" serched from https://nodejs.org/download/nightly/ . Whats your thoughts on this?

//cc @tarungarg546

**Comment by hemanth** [comment]
I feel it would be great to find the latest version in the directory structure for a given os version and have 0 inputs from the user.

**Comment by tarungarg546** [comment]
+1 @hemanth @cswl

**Comment by vladikoff** [comment]
Is there a workaround until there is a released fix?

**Comment by hemanth** [comment]
Okies, not we can integrate [this](https://github.com/hemanth/node-nightly-versions)?  😇

**Comment by hemanth** [comment]
I have updated the master with the latest changes, yet to do a release, if someone can confirm me that it looks fine on windows, we can do it!

**Comment by bhaveshgohel** [comment]
@hemanth Please check https://github.com/hemanth/node-nightly-version/commit/9acedb40e536e93b50dadf975a161ff6c98a66cf#commitcomment-18666823

**Comment by tarungarg546** [comment]
Tracking link https://github.com/hemanth/node-nightly-version/pull/3

**Comment by hemanth** [comment]
Okies, all is well for a version bump now?

**Comment by tarungarg546** [comment]
+ @bvjebin @vladikoff

**Comment by hemanth** [comment]
We so badly need a `@here` or `@all` 🤔

**Comment by bhaveshgohel** [comment]
@hemanth @tarungarg546  Sorry for the late reply, I was getting undefined version on windows, so add some changes and sent two PR, Please Track the update here: https://github.com/hemanth/node-nightly-version/issues/4

PR1 : https://github.com/hemanth/node-nightly-versions/pull/2
PR2: https://github.com/hemanth/node-nightly-version/pull/5

**Comment by hemanth** [comment]
Thanks! 

I think with this, we must be good for a `minor` version bump for `node-nigthly`, let us close this issue ASAP!

**Comment by bhaveshgohel** [comment]
Yes! :+1:

**Comment by hemanth** [comment]
[Hmm](https://travis-ci.org/hemanth/node-nightly/jobs/154060540#L273) 🤔

**Comment by bhaveshgohel** [comment]
I get the same error after complete clean install :confused: 

![npm-bug](https://cloud.githubusercontent.com/assets/5253753/17846135/5e9bf236-6864-11e6-8215-8689bb230f03.jpg)

known bug : https://github.com/npm/npm/issues/9633 (╯°□°）╯︵ ┻━┻

**Comment by hemanth** [comment]
Green at last! Phew!

**Comment by hemanth** [comment]
`node-nightly@1.6.0` fixes this, thanks for reporting.

**Comment by hemanth** [comment]
TODO: Write the changelog and tweet about it!

**Comment by bhaveshgohel** [comment]
🐦 On Twitter as  [ibhaveshgohel](https://twitter.com/ibhaveshgohel)

**Comment by tarungarg546** [comment]
[Tarun_garg2](https://twitter.com/tarun_garg2)

**Comment by hemanth** [comment]
I just added a change log [History](https://github.com/hemanth/node-nightly/blob/master/History.md) file.

I wonder if @cswl is on twitter...🤔
