### ISSUE TITLE
How to inspect existing multi-arg bin commands from other cli tools.

### ISSUE THREAD

**Issue by TheLarkInn** [hemanth/node-nightly#3]
Nice job on this guys. 

I'm working on the angular-cli and I'd like to be able to debug some of the commands we use like:
`ng build`
`ng serve`
`ng build --watch --environment='subtropical'` 

I use node nightly like the following: 
`node-nightly --inspect --debug-brk ng build`

However it looks like only the `ng` is picked up and not the secondary command. Any advice?

**Comment by hemanth** [comment]
@TheLarkInn Basically the command opts and flags gets pass to the node binary as in.

It boils down to an `execvp` call to `node` with `[ '--inspect', '--debug-brk', 'ng', 'build' ]`

//cc @paulirish.

**Comment by TheLarkInn** [comment]
```
→ node-nightly --inspect --debug-brk $(ng build)
zsh: argument list too long: node-nightly
```
I think that takes the obnoxious output from that `ng build` command and adds it in the arg list thus the error.

**Comment by hemanth** [comment]
Looks like, try asking at #angular

**Comment by TheLarkInn** [comment]
I'm on the angular-cli team lol. I'll have to see what that command evaluates to and see if I can run it manually.

**Comment by hemanth** [comment]
![adorable-lovely-de-o7sgkGyXm2Xrq](https://camo.githubusercontent.com/403f70eacc96aa1e4427dc7077cad1208b85e11a/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6f3773676b4779586d325872712f67697068792e676966>)

**Comment by TheLarkInn** [comment]
@hemanth lol!!!! 

After a bit of digging it turns out that having aliased bin commands in your path don't really work. 

So: 
`node-nightly --inspect --debug-brk node_modules/angular-cli/bin/ng build`

vs 

`node-nightly --inspect --debug-brk ng build`

So I got my dealio working and its amazing. That inspector speed is FAST.

**Comment by TheLarkInn** [comment]
![Alt Text](http://www.sheawong.com/wp-content/uploads/2013/08/keephatin.gif)

**Comment by hemanth** [comment]
![cat-lovs-mousy-13Rgcvb54ffxAc](https://camo.githubusercontent.com/5d2410696f2837243740917c0d415c8bdc06bdbb/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f31335267637662353466667841632f67697068792e676966>)
