### ISSUE TITLE
Adjust command line options

### ISSUE THREAD

**Issue by krokofant** [hemanth/node-nightly#39]
Related to #36 

I propose that `--version` outputs the currently used version and that something like `--use` would decide which version to install &/ use. This would be be more clear and follow the common `--version` convention for displaying version information.

**Comment by hemanth** [comment]
Yeah that would be a good beat, but how many of them would like to switch between nightly versions?

**Comment by krokofant** [comment]
@hemanth I don't know but it's not relevant to the changing if the keywords.

`node-nightly --version {version}` -> `node-nightly --use {version}`
`node-nightly --version {version}` -> should display the currently installed nightly so one knows which works, is broken, etc.

**Comment by hemanth** [comment]
Wow! This went unnoticed in the barrage of issues.
