### ISSUE TITLE
errors when upgrade

### ISSUE THREAD

**Issue by neal1991** [hemanth/node-nightly#40]
After installing node-nightly, when I try to execute `node-nightly` it indicates to upgrade. But when I try to execute `node-nightly --upgrade':
```
node-nightly --upgrade
Checking for update...
Deleting old version
Deleted!
Installing newer version..
{ Error: EPERM: operation not permitted, rename 'C:\Users\neal1\AppData\Roaming\npm\node_modules\node-nightly\node-v8.0.0-nightly2017051384fc069b95-win-x64' -> 'C:\Users\neal1\AppData\Roaming\npm\node_modules\node-nightly\node-nightly'
    at fs.renameSync (fs.js:776:18)
    at download.then._ (C:\Users\neal1\AppData\Roaming\npm\node_modules\node-nightly\index.js:45:9)
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\neal1\\AppData\\Roaming\\npm\\node_modules\\node-nightly\\node-v8.0.0-nightly2017051384fc069b95-win-x64',
  dest: 'C:\\Users\\neal1\\AppData\\Roaming\\npm\\node_modules\\node-nightly\\node-nightly' }
```
My OS is win10 and my node version is 7.9.0. And I have tried two solutions:
1. execute `npm cache clean`
2. disable avast in my computer
Unfortunately, both do not work at all.

**Comment by hemanth** [comment]
Looks like permission issues, try opening your terminal with admin
privileges.

**Comment by neal1991** [comment]
@hemanth I have tried before, does not work still. And I am really confused that why it indicates upgrade just after I install.

**Comment by neal1991** [comment]
@hemanth Hi, I have found something new. So here is the whole process of the problem. Firstly, when it tried to delete the old version folder by `rm.sync('./node-nightly')`. And then it would rename the hash version folder to `node-nightly`. However, the truth is the old version folder had not been deleted at all. And there was no detection for the old version folder. It had thought it has been deleted.
The problem seems that `rm.sync('./node-nightly)` does not work. So I make this [pr](https://github.com/hemanth/node-nightly/pull/41). I wish that you can review it. Thanks.
