### ISSUE TITLE
latest not on npm?

### ISSUE THREAD

**Issue by paulirish** [hemanth/node-nightly#7]
So weird..

![image](https://cloud.githubusercontent.com/assets/39191/16501122/c78415e8-3ebc-11e6-805b-54cefdcbe0b2.png)

locally i have 1.3.0

but i see https://www.npmjs.com/package/node-nightly says 1.3.1

and the repo has 1.3.2

:/

and 1.3.0 is def broken for me. 

erg sorry for all the back and forth on this one.

**Comment by paulirish** [comment]
btw just published the updates to the post
![image](https://cloud.githubusercontent.com/assets/39191/16501541/b8f974da-3ebe-11e6-9f7c-fe41bd848997.png)

**Comment by hemanth** [comment]
@paulirish It's up and running, thanks!
